### ISSUE TITLE
component example

### ISSUE THREAD

**Issue by zejiang0jason** [RT-Thread-packages/webclient#11]
Is there example for this component? thanks.

**Comment by Lawlieta** [comment]
Not yet, but it will soon be added.

**Comment by zejiang0jason** [comment]
ok, thanks.

**Comment by armink** [comment]
samples is coming https://github.com/RT-Thread-packages/webclient/tree/master/samples

**Comment by armink** [comment]
这里还有很全面的文档介绍：https://github.com/RT-Thread-packages/webclient/tree/master/docs

**Comment by armink** [comment]
许可也做了修改，现在是 Apache-2.0 ，issue 我先关闭了，后续还有问题再打开
