### ISSUE TITLE
上传/下载文件函数  能获取的参数太少

### ISSUE THREAD

**Issue by SunXofRTT** [RT-Thread-packages/webclient#19]
1.webclient_post_file()/webclient_get_file()函数中，能否添加header入参，允许外部设定header
2.webclient_post_file()能否返回出一系列数据，比如： 开发者服务器返回的数据 和 http状态码
3.能否提供监控文件传输的进度的接口或者参数
4. 能否提供中断文件传输的接口

**Comment by armink** [comment]
先试用下 V2.0 最新版，文档里也有迁移说明。如果有问题再重新说明下

**Comment by armink** [comment]
如果没有问题，issue 先关闭，有需要的话再打开

**Comment by flyranchao** [comment]
你好：
上传和下载的测试sample哪里有呢？
监控文件传输的进度的接口或者参数有了吗？
