### ISSUE TITLE
访问主页时，如果路径末尾没有/，访问会失败。

### ISSUE THREAD

**Issue by aozima** [RT-Thread-packages/webclient#59]
示例

## 失败的示例
```
http://www.rt-thread.org
http://www.rt-thread.org:80
```

## 成功的示例
```
http://www.rt-thread.org/
http://www.rt-thread.org:80/
```

在浏览器上面测试，发现浏览器会自动加上末尾的 /。
如果URL是手动输入或编码，可以要求使用者必须有加/。但在项目中有遇到服务器下发的URL也是不带/的。因此，可以考虑在 webclient中添加这个功能。

**Comment by Lawlieta** [comment]
应该是 webclient_resolve_address 函数中解析的 request_url 地址问题，可以考虑添加该功能
