### ISSUE TITLE
https测试找不到mbedtls的部分接口

### ISSUE THREAD

**Issue by flyranchao** [RT-Thread-packages/webclient#64]
你好！
　从社区下载的mbedtls和webclient，测试webclient的https功能时，发现打开宏WEBCLIENT_USING_MBED_TLS后，编译找不到tls_client.h文件．
1.这个文件是自定义的吗？
2.另外发现webclient/src/webclient.c中使用的mbedtls的接口:
mbedtls_client_init
mbedtls_client_read
mbedtls_client_write
mbedtls_client_connect
mbedtls_client_context
mbedtls_client_close
都不存在．这些接口也是要自己定义的吗？
--

麻烦指导一下，谢谢！

**Comment by Lawlieta** [comment]
tls_client.c/.h 文件是 mbedtls 默认添加进编译的文件，你是不是没有通过 EMV 工具，直接将两个软件包加到工程中导致缺少相关宏定义，如果是，可以学习一下 EMV 的使用方式，官方文档如下https://www.rt-thread.org/document/site/programming-manual/env/env/

**Comment by flyranchao** [comment]
tls_client.c/.h 文件在rtt整个sdk源码中都没有呢，我的是ubuntu的环境开发，使用env工具不是很方便．
emm

**Comment by Lawlieta** [comment]
tls_client.c 在 mbedtls 软件包 mebdtls/ports/src 目录下，Ubuntun 中也可以使用 ENV 工具，如果不想使用，建议搞清楚 webclient 和 mebdtls 软件包中需要的文件，手动添加一下

**Comment by flyranchao** [comment]
mbedtls 软件包 mebdtls/ports/src 目录下,应该还是依赖于ENV工具吧．我从rtt的github下载的mbedtls也是没有tls_client.h/tls_client.c文件的，没有ports目录．

**Comment by aozima** [comment]
https://github.com/RT-Thread-packages/mbedtls

https://github.com/RT-Thread-packages/mbedtls/blob/b460bbae4f744cb257486146ef688fe3be62d9fc/ports/src/tls_client.c#L70
