### ISSUE TITLE
如果用GCC编译会报错

### ISSUE THREAD

**Issue by fortunerains** [RT-Thread-packages/webclient#78]
![image](https://user-images.githubusercontent.com/24492495/130588097-9aca3733-c072-4546-be3e-dfecb3d52892.png)
原因没有包含errno.h 头文件，将该头文件加到
![image](https://user-images.githubusercontent.com/24492495/130588216-871457c5-b4ba-4ebd-8448-7f9f7919908c.png)
不报错了

**Comment by aozima** [comment]
可能和RT-Thread版本有关，你用的哪个版本呢？

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread-packages/webclient/pull/79

**Comment by xiangxistu** [comment]
![image](https://user-images.githubusercontent.com/52819708/132151661-2629fa7e-1a8a-4caf-996d-eedf81fef21d.png)

LIBC 这块有些改动，现在主版本已经支持了。
